apiVersion: apps/v1
kind: Deployment
metadata:
  name: vbserver-deployment
spec:
  template:
    spec:
      containers:
      - env:
        - name: MAX_CONNS
          value: "256"
        name: vbserver-container
          